apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiblZ5WW1WckxYTnZlbTlsZGpwbmFIQmZkM00wTW5KMWIxWk9SVXhrZGtkcFNGUkNjWFZxYUdOVmVEaEdhM1prTXpGbVJHZGsiCgkJfQoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJwb2RtYW4iLAoJImNsaVBsdWdpbnNFeHRyYURpcnMiOiBbCgkJIi9vcHQvaG9tZWJyZXcvbGliL2RvY2tlci9jbGktcGx1Z2lucyIKCV0KfQo=
type: kubernetes.io/dockerconfigjson
