apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: cinemaabyss
  labels:
    app: events-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
      version: v1
  template:
    metadata:
      labels:
        app: events-service
        version: v1
    spec:
      containers:
      - name: events-service
        image: ghcr.io/nurbek-sozoev/architecture-cinemaabyss/events-service:latest
        ports:
        - containerPort: 3282
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3282"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: KAFKA_CLIENT_ID
          value: "events-service"
        - name: LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /api/events/health
            port: 3282
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/events/health
            port: 3282
          initialDelaySeconds: 15
          periodSeconds: 10
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: cinemaabyss
  labels:
    app: events-service
spec:
  type: ClusterIP
  ports:
  - port: 3282
    targetPort: 3282
    protocol: TCP
    name: http
  selector:
    app: events-service
