apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service
  namespace: cinemaabyss
  labels:
    app: movies-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies-service
      version: v1
  template:
    metadata:
      labels:
        app: movies-service
        version: v1
    spec:
      containers:
      - name: movies-service
        image: ghcr.io/sozoev/architect-sprint2/movies-service:latest
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "cinemaabyss"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: movies-service
  namespace: cinemaabyss
  labels:
    app: movies-service
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: movies-service