apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-service
  namespace: cinemaabyss
  labels:
    app: movies-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-service
      version: v1
  template:
    metadata:
      labels:
        app: movies-service
        version: v1
    spec:
      containers:
      - name: movies-service
        image: ghcr.io/nurbek-sozoev/architecture-cinemaabyss/movies-service:latest
        ports:
        - containerPort: 3281
        env:
        - name: PORT
          value: "3281"
        - name: DB_CONNECTION_STRING
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=disable"
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /api/movies/health
            port: 3281
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/movies/health
            port: 3281
          initialDelaySeconds: 15
          periodSeconds: 10
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: movies-service
  namespace: cinemaabyss
  labels:
    app: movies-service
spec:
  type: ClusterIP
  ports:
  - port: 3281
    targetPort: 3281
    protocol: TCP
    name: http
  selector:
    app: movies-service