{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
        app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations: {}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: dockerconfigsecret
      {{- end }}
      containers:
      - name: proxy-service
        image: {{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}
        imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.proxyService.service.targetPort }}
          name: proxy
          protocol: TCP
        env:
        # Node.js настройки
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "{{ .Values.proxyService.service.targetPort }}"
        - name: HOST
          value: "0.0.0.0"
        
        # Gateway конфигурация
        - name: CORS_ENABLED
          value: "true"
        - name: LOG_LEVEL
          value: "info"
        
        # Сервисы для роутинга
        - name: MONOLITH_SERVICE_URL
          value: "http://monolith:{{ .Values.monolith.service.port }}"
        - name: MOVIES_SERVICE_URL
          value: "http://movies-service:{{ .Values.moviesService.service.port }}"
        
        # Переменные для отслеживания миграции Strangler Fig
        - name: GRADUAL_MIGRATION
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: GRADUAL_MIGRATION
        - name: MOVIES_MIGRATION_PERCENT
          valueFrom:
            configMapKeyRef:
              name: cinemaabyss-config
              key: MOVIES_MIGRATION_PERCENT
        
        resources:
          {{- toYaml .Values.proxyService.resources | nindent 10 }}
        
        livenessProbe:
          httpGet:
            path: /gateway/health
            port: proxy
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /gateway/health
            port: proxy
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3

      restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.proxyService.service.type }}
  ports:
  - port: {{ .Values.proxyService.service.port }}
    targetPort: {{ .Values.proxyService.service.targetPort }}
    protocol: TCP
    name: proxy
  selector:
    app: proxy-service
{{- end }}
