# Global settings
global:
  namespace: cinemaabyss
  domain: cinemaabyss.example.com

# Image pull secrets
imagePullSecrets:
  dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiblZ5WW1WckxYTnZlbTlsZGpwbmFIQmZkM00wTW5KMWIxWk9SVXhrZGtkcFNGUkNjWFZxYUdOVmVEaEdhM1prTXpGbVJHZGsiCgkJfQoJfSwKCSJjdXJyZW50Q29udGV4dCI6ICJwb2RtYW4iLAoJImNsaVBsdWdpbnNFeHRyYURpcnMiOiBbCgkJIi9vcHQvaG9tZWJyZXcvbGliL2RvY2tlci9jbGktcGx1Z2lucyIKCV0KfQo=
# Database configuration
database:
  host: postgres
  port: 5432
  name: cinemaabyss
  user: postgres
  password: cG9zdGdyZXNfcGFzc3dvcmQ=
  image:
    repository: postgres
    tag: 14
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

# Proxy service configuration
proxyService:
  enabled: true
  image:
    repository: ghcr.io/nurbek-sozoev/architecture-cinemaabyss/proxy-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 3200
    targetPort: 3200
    type: ClusterIP

# Monolith configuration
monolith:
  enabled: true
  image:
    repository: ghcr.io/nurbek-sozoev/architecture-cinemaabyss/monolith
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 3280
    targetPort: 3280
    type: ClusterIP

# Movies service configuration
moviesService:
  enabled: true
  image:
    repository: ghcr.io/nurbek-sozoev/architecture-cinemaabyss/movies-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 3281
    targetPort: 3281
    type: ClusterIP

# Events service configuration
eventsService:
  enabled: true
  image:
    repository: ghcr.io/nurbek-sozoev/architecture-cinemaabyss/events-service
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 3282
    targetPort: 3282
    type: ClusterIP

# Kafka configuration
kafka:
  enabled: true
  image:
    repository: wurstmeister/kafka
    tag: 2.13-2.7.0
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
  topics:
    - name: cinema-events
      partitions: 1
      replicationFactor: 1

# Zookeeper configuration
zookeeper:
  enabled: true
  image:
    repository: wurstmeister/zookeeper
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: cinemaabyss.example.com
      paths:
        - path: /
          pathType: Prefix
          service: proxy-service
          port: 3200

# Application configuration
config:
  # Strangler Fig configuration
  gradualMigration: "true"
  moviesMigrationPercent: "50"
